name: Book Management Deployment

on:
  push:
    branches:
      - main  # Trigger on merges to the main branch

jobs:
  deploy:
    name: Deploy Book Management App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package index and install dependencies
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # Add Docker's official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

            # Install Docker
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            # Add the SSH user to the Docker group
            sudo usermod -aG docker ubuntu
            
            # Install Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Verify installations
            sudo docker --version
            sudo docker-compose --version

            # Navigate to the project directory and deploy
            cd /home/ubuntu/
            git clone https://github.com/Humaidu/fastapi-book-project.git
            cd fastapi-book-project/
            git pull

            # Stop and remove any existing containers
            sudo docker-compose down
            
            # Remove any leftover containers with the same name
            sudo docker rm -f fastapi-app || true
            
            # Start fresh
            sudo docker-compose up -d --build
